--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "Join our community on Discord and find other Stylizers"
    name: "Chat Discord"
    url: "https://discord.gg/uqCAHnud"
  - 
    about: "Start a discussion in the GitHub Discussions"
    name: "Start a new discussion"
    url: "https://github.com/stylizedjs/stylized/discussions/new"
  - 
    about: "Visit our website and learn more about Stylized"
    name: Website
    url: "https://stylized.dev"
